language: cpp
dist: xenial
compiler: gcc
sudo: required

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

before_install:
    - eval "${MATRIX_EVAL}"
    - sudo apt-get install -y cmake
    - sudo add-apt-repository ppa:mhier/libboost-latest -y
    - sudo apt-get update -q
    - sudo apt-get install -y libboost1.68
    - ./install-catch2.sh

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make -j
  - test/tests
