#   Copyright 2019 Ethereum Foundation
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

image: Visual Studio 2017
platform: x64

install:
  - cd c:\tools\vcpkg
  - vcpkg install boost:x64-windows
  - vcpkg install catch2:x64-windows
  - vcpkg integrate install

cache:
  - C:\tools\vcpkg\installed -> .appveyor.yml

before_build:
  - cd "%APPVEYOR_BUILD_FOLDER%"
  - cmake -H. -BBuild -A%PLATFORM% -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake

build:
  project: Build\silkworm.sln

test_script:
  - cd Build
  - ctest -V -j
